[package]
name = "waysaver"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
gtk4 = { version = "0.9.6", features = ["v4_12"] }
gdk4-wayland = "0.9.6"
gtk4-layer-shell = "0.5.0"
webkit6 = "0.4.0"
clap = { version = "4.5.40", features = ["derive"] }